services:
  db:
    image: postgres
    volumes:
      - zalon_design_volume:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db

  celery:
    restart: always
    build: .
    command: celery -A backend.celery worker -l info -c 1
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

  celery-beat:
    restart: always
    build: .
    command: celery -A backend.celery beat -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  zalon_design_volume:
  redis_data:

networks:
  default:
    name: zalon_design_network
