# Generated by Django 4.2.3 on 2024-03-25 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illustration',
            name='name',
        ),
    ]
