# Generated by Django 4.2.3 on 2024-03-27 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pack_banner_alter_illustration_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('business', models.CharField(max_length=100, verbose_name='Empresa')),
                ('review', models.TextField(verbose_name='Reseña')),
                ('image', models.ImageField(null=True, upload_to='reviews', verbose_name='Imagen')),
                ('pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.pack', verbose_name='Pack')),
            ],
        ),
    ]
