# Generated by Django 4.2.3 on 2024-03-30 00:24

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customerreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.pack', verbose_name='Pack'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción'),
        ),
    ]
