# Generated by Django 4.2.3 on 2024-03-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customerreview_pack_alter_pack_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='banner',
        ),
        migrations.AddField(
            model_name='pack',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Carátula'),
        ),
    ]
