# Generated by Django 4.2.3 on 2024-03-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_pack_banner_pack_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='cover',
            field=models.ImageField(upload_to='covers', verbose_name='Carátula'),
        ),
    ]
