# Generated by Django 4.2.3 on 2024-03-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_pack_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerreview',
            options={'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AlterField(
            model_name='pack',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Precio'),
        ),
    ]
