# Generated by Django 4.2.3 on 2024-04-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customer_remove_customerreview_business_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='packsale',
            old_name='date',
            new_name='created_at',
        ),
    ]
