# Generated by Django 4.2.3 on 2024-04-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='image',
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='customers', verbose_name='Foto'),
        ),
    ]
