# Generated by Django 4.2.3 on 2024-04-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_customerreview_pack'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackSale',
            new_name='Order',
        ),
    ]
