# Generated by Django 4.2.3 on 2024-05-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_pack_show_in_landing_order_instructions_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='instructions_file',
        ),
        migrations.AddField(
            model_name='pack',
            name='instructions_file',
            field=models.FileField(blank=True, null=True, upload_to='instructions', verbose_name='Archivo de instrucciones'),
        ),
    ]
