# Generated by Django 4.2.3 on 2024-05-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_order_instructions_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='instructions_file',
            field=models.FileField(default=None, null=True, upload_to='instructions', verbose_name='Archivo de instrucciones'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='subtitle',
            field=models.CharField(default=None, max_length=100, verbose_name='Subtítulo'),
        ),
    ]
