# Generated by Django 4.2.3 on 2024-05-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_order_instructions_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='instructions_file',
            field=models.FileField(upload_to='instructions', verbose_name='Archivo de instrucciones'),
        ),
    ]
