# Generated by Django 4.2.3 on 2024-05-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_pack_instructions_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='subtitle',
            field=models.CharField(max_length=100, verbose_name='Subtítulo'),
        ),
    ]
