# Generated by Django 4.2.3 on 2024-05-03 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_payment"),
        ("main", "0021_contact_created_at"),
    ]

    operations = []
