# Generated by Django 4.2.3 on 2024-05-03 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_merge_0020_payment_0021_contact_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
    ]
