# Generated by Django 4.2.3 on 2024-05-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_contactmsg_delete_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmsg',
            options={'verbose_name': 'Mensaje de contacto', 'verbose_name_plural': 'Mensajes de contacto'},
        ),
    ]
