# Generated by Django 4.2.3 on 2024-05-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_contactmsg_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
    ]
