# Generated by Django 4.2.3 on 2024-05-03 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='Tiene reseña'),
        ),
    ]
