# Generated by Django 4.2.3 on 2024-05-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_customerreview_score_order_is_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='photo',
        ),
    ]
