# Generated by Django 4.2.3 on 2024-05-04 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_customer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación'),
        ),
    ]
