# Generated by Django 4.2.3 on 2024-05-04 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_customerreview_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='score',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación'),
        ),
    ]
