# Generated by Django 4.2.3 on 2024-05-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_customerreview_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='illustration',
            options={'verbose_name': 'Ilustración', 'verbose_name_plural': 'Galería'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='business',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='instructions_file',
            field=models.FileField(upload_to='instructions', verbose_name='PDF de Pack'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Precio de oferta'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='strikethrough_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Precio regular'),
        ),
    ]
