# Generated by Django 4.2.3 on 2024-05-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_illustration_options_alter_customer_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='subtitle',
            field=models.CharField(default='', max_length=100, verbose_name='Descripción corta'),
        ),
    ]
