# Generated by Django 4.2.3 on 2024-06-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_pack_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='custom_url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='URL personalizada'),
        ),
    ]
