# Generated by Django 4.2.3 on 2024-06-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_pack_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='custom_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL personalizada'),
        ),
    ]
