# Generated by Django 4.2.3 on 2024-06-18 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_pack_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='custom_url',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_custom_url', message='URL personalizada debe contener solo letras, números, guiones y guiones bajos.', regex='^[\\w-]+$')], verbose_name='URL personalizada'),
        ),
    ]
