# Generated by Django 4.2.3 on 2024-06-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_pack_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
