# Generated by Django 4.2.3 on 2024-06-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_pack_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_request_sent',
            field=models.BooleanField(default=False, verbose_name='Solicitud de reseña enviada'),
        ),
    ]
